// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh9jnVS320BLfUqAKCVHH6GjVqgowHGd8',
    appId: '1:961494742721:web:454602f8f87e24cfe2c640',
    messagingSenderId: '961494742721',
    projectId: 'nusketch',
    authDomain: 'nusketch.firebaseapp.com',
    storageBucket: 'nusketch.appspot.com',
    measurementId: 'G-3VH2X62QGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-LTjz0R83VB6q3t9C26-80ZijDlIVqI',
    appId: '1:961494742721:android:ed9e56a85e431730e2c640',
    messagingSenderId: '961494742721',
    projectId: 'nusketch',
    storageBucket: 'nusketch.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJg7MzEv3a0TjJMbgmOop34xkF5OO2cs',
    appId: '1:961494742721:ios:5ec411f9eeac16c1e2c640',
    messagingSenderId: '961494742721',
    projectId: 'nusketch',
    storageBucket: 'nusketch.appspot.com',
    iosClientId: '961494742721-peiuiul2cqtlbfm4bbgonb1pimltr0kt.apps.googleusercontent.com',
    iosBundleId: 'com.nusketch',
  );
}
